# Generated by Django 5.0.6 on 2024-06-15 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('apellidos', models.CharField(max_length=40)),
                ('edad', models.IntegerField()),
                ('telefono', models.CharField(max_length=9)),
                ('direccion', models.CharField(max_length=40)),
            ],
        ),
    ]
